# Generated by Django 3.2.25 on 2025-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='Aa@123456'),
            preserve_default=False,
        ),
    ]
