# Generated by Django 4.2.23 on 2025-07-24 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_followings', '0001_initial'),
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='user_followings.UserFollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
